data:
  path_to_data: C:\Users\heylu\Documents\github\A Study Case About Mental Health Tweets in Pandemic Times\data\6. Dataframes
  train_filename: dataset_train.csv
  test_filename: dataset_test.csv
  validation_filename: dataset_valid.csv
  path_to_test_pred_scores: data/output/pred.txt

model:
  model_name: neuralmind/bert-base-portuguese-cased
  max_seq_length: 128
  learning_rate: 2e-5
  num_epochs: 10  
  num_warmup_steps: 0 
  batch_size: 64 